project:
  type: website

website:
  title: "<b>ElementR</b>"
  favicon: img/ElementR.png
  twitter-card: true
  site-url: https://elementr.gitpages.huma-num.fr/website/
  page-navigation: true
  navbar:
    background: "#1a8d73"
    right:
      - href: pgm.qmd
        text: Programme
      - text: Matériel
        menu:
          - href: session1.qmd
            text: Séance introductive
          - href: session2.qmd
            text: Séance 2
      - href: about.qmd
        text: Á propos
    tools:
      - icon: github
        href: https://gitlab.huma-num.fr/elementr/website
  sidebar:
    contents:
      - session.qmd
      - session1.qmd
      - session2.qmd   
      - href: about.qmd
        text: Á propos
  page-footer: ElementR © UMR Géographie-Cités · UMR PRODIG · UAR RIATE
  margin-header: |
    ![](img/ElementR.png)


format:
  html:
    theme: 
      light: Minty
      dark: cyborg
    css: styles.css
    toc: true
    page-layout: full

editor: visual

