project:
  type: website
lang: fr
website:
  title: "<b>ElementR</b>"
  favicon: img/ElementR.png
  twitter-card: true
  site-url: https://elementr.gitpages.huma-num.fr/website/
  description: "Site web du groupe d’utilisateur·rice·s ElementR"
  page-navigation: true
  search: 
    location: navbar
    type: overlay
  navbar:
    background: "#1a8d73"
    left: 
      - href: programme.qmd
        text: Programme
      - href: seance.qmd
        text: Ressources
      - href: apropos.qmd
        text: Á propos
    right:
      - href: contact.qmd
        text: Contact
    tools:
      - icon: git
        aria-label: GitLab
        text: GitLab
        href: https://gitlab.huma-num.fr/elementr/website
  sidebar:
    contents:
      - programme.qmd
      - seance.qmd
      - href: posts/seance1.qmd
        text: Introduction ElementR
      - href: posts/seance2.qmd 
        text: Initiation à R (1)
      - href: posts/seance3.qmd
        text: Initiation à R (2)
  page-footer: ElementR 2022 - [![licensebuttons by-nc](https://licensebuttons.net/l/by-nc/4.0/80x15.png)](https://creativecommons.org/licenses/by-nc/4.0) - UMR Géographie-Cités · UMR PRODIG · UAR RIATE
  margin-header: |
    ![](img/ElementR.png)

format:
  html:
    theme: 
      light: Minty
      dark: cyborg
    css: styles.css
    toc: true
    page-layout: full
    include-in-header:
      file: matomo_tracking.html

editor: visual

