project:
  type: website

website:
  title: "ElementR"
  navbar:
    background: "#1a8d73"
    right:
      - href: pgm.qmd
        text: Programme
      - text: Matériel
        menu:
          - href: session1.qmd
            text: Séance 1
          - href: session2.qmd
            text: Séance 2
      - href: about.qmd
        text: Á propos
    tools:
      - icon: github
        href: https://gitlab.huma-num.fr/elementr/website
  sidebar:
    contents:
      - session.qmd
      - session1.qmd
      - session2.qmd   
      - href: about.qmd
        text: Á propos
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

